### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by jam3ternal** [JRQLS/ToClash#3]
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:\Users\a1293\Downloads\ToClash-master\SS_clash(from ss Local configuration file)\SS_clash.py 
Traceback (most recent call last):
  File "C:\Users\a1293\Downloads\ToClash-master\SS_clash(from ss Local configuration file)\SS_clash.py", line 135, in <module>
    nodes = getallNodes(file)
  File "C:\Users\a1293\Downloads\ToClash-master\SS_clash(from ss Local configuration file)\SS_clash.py", line 31, in getallNodes
    if checkObfs(obfs) and checkPro(protocol):
  File "C:\Users\a1293\Downloads\ToClash-master\SS_clash(from ss Local configuration file)\SS_clash.py", line 51, in checkObfs
    if str == "plain" or str.split('_')[-1] == "compatible":
AttributeError: 'NoneType' object has no attribute 'split'
>>>

**Comment by jongkhurunn** [comment]
我也是这样
