### ISSUE TITLE
binascii.Error: Incorrect padding

### ISSUE THREAD

**Issue by ApocalypseYun** [JRQLS/ToClash#4]
C:\Users\42077>"D:/Program Files/Python/Python3/python.exe" "d:/Downloads/ToClash-master/SS_clash(from ss subscription)/SS_clash.py"
Traceback (most recent call last):
  File "d:/Downloads/ToClash-master/SS_clash(from ss subscription)/SS_clash.py", line 182, in <module>
    nodes = getAllNodes(url)
  File "d:/Downloads/ToClash-master/SS_clash(from ss subscription)/SS_clash.py", line 28, in getAllNodes
    links = getAllLinks(url)
  File "d:/Downloads/ToClash-master/SS_clash(from ss subscription)/SS_clash.py", line 19, in getAllLinks
    result = decodeInfo(links)
  File "d:/Downloads/ToClash-master/SS_clash(from ss subscription)/SS_clash.py", line 123, in decodeInfo
    result = str(base64.urlsafe_b64decode(info))
  File "D:\Program Files\Python\Python3\lib\base64.py", line 133, in urlsafe_b64decode
    return b64decode(s)
  File "D:\Program Files\Python\Python3\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

**Comment by lancelotly** [comment]
> C:\Users\42077>"D:/Program Files/Python/Python3/python.exe" "d:/Downloads/ToClash-master/SS_clash(from ss subscription)/SS_clash.py"
> Traceback (most recent call last):
> File "d:/Downloads/ToClash-master/SS_clash(from ss subscription)/SS_clash.py", line 182, in
> nodes = getAllNodes(url)
> File "d:/Downloads/ToClash-master/SS_clash(from ss subscription)/SS_clash.py", line 28, in getAllNodes
> links = getAllLinks(url)
> File "d:/Downloads/ToClash-master/SS_clash(from ss subscription)/SS_clash.py", line 19, in getAllLinks
> result = decodeInfo(links)
> File "d:/Downloads/ToClash-master/SS_clash(from ss subscription)/SS_clash.py", line 123, in decodeInfo
> result = str(base64.urlsafe_b64decode(info))
> File "D:\Program Files\Python\Python3\lib\base64.py", line 133, in urlsafe_b64decode
> return b64decode(s)
> File "D:\Program Files\Python\Python3\lib\base64.py", line 87, in b64decode
> return binascii.a2b_base64(s)
> binascii.Error: Incorrect padding

Please double-check the subscription link file that can be base64 decoded. 
The "decodeInfo(info)" impacts your error.
